version: '3.4'
services:
  keycloak:
    container_name: keycloak-container
    image: jboss/keycloak:11.0.0
    volumes:
      - ./keycloak-server/realm-export.json:/tmp/keycloak/config/realm-export.json
    environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        KEYCLOAK_IMPORT: /tmp/keycloak/config/realm-export.json
    ports:
      - "18080:18080"
    restart: on-failure
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - "9200:9200"
    restart: on-failure
  zipkin:
    container_name: zipkin-container
    image: openzipkin/zipkin-slim
#    command: docker run -d -p 9411:9411 openzipkin/zipkin
    ports:
      - "9411:9411"
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data