server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: orchestratorModule
          uri: lb://orchestrator-service
          predicates:
            - Path=/orchestrator/**
        - id: authenModule
          uri: lb://authen-service
          predicates:
            - Path=/authen/**